apiVersion: v2
name: nginx-internal
description: Internal NGINX Ingress Controller
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: ingress-nginx
    version: 4.7.1
    repository: https://kubernetes.github.io/ingress-nginx