apiVersion: v2
name: cert-manager
description: Certificate management for Kubernetes
type: application
version: 0.1.0
appVersion: "1.12.0"
dependencies:
  - name: cert-manager
    version: v1.12.3
    repository: https://charts.jetstack.io